name: Deployment Pipline on push updates

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
            sparse-checkout: '/client'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
 
      - name: Build application
        run: npm run build
        
      - name: Deploy to S3
        run: aws s3 sync ./* s3://${{ secrets.BUCKET_ID }}